# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            blm.io
tagline:
url:              http://blmoore.github.io
paginate:         7
baseurl:          /blog
author:
  name:           Ben Moore
  url:            https://twitter.com/benjaminlmoore
  email:          root@blm.io

# Related
lsi:              true