# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            blm.io
tagline:
url:              http://blm.io/blog
paginate:         1
baseurl:          http://blm.io
author:
  name:           Ben Moore
  url:            https://twitter.com/benjaminlmoore
  email:          root@blm.io
